[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["chromium", "chromium-driver"]

[deploy]
startCommand = "playwright install chromium && python bot/main.py"
restartPolicyType = "always"
